### PR TITLE
A ton of little fixes and API normalization

### LINKED ISSUE #275: Data parsing/massaging of events pages
Dates for project cards, pulling in github avatars, etc.

### PR DESCRIPTION
**Pull request by alanmoo**
Closes #275,  #120 

giphy

### CODE REVIEW

File: app/js/humanizeDates.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import Moment from "moment-timezone";
```
Comment (gvn) [inline app/js/humanizeDates.js]: Minor nit: We're using lower-hyphen-case for filenames.

File: app/react/components/github-avatar/github-avatar.scss [hunk 2]
```diff
@@ -1,6 +1,9 @@
 .github-avatar {
-  border-radius: 50%;
+  display: inline-block;
   margin-bottom: 1rem;
+  > img {
```
Comment (gvn) [inline app/react/components/github-avatar/github-avatar.scss]: I added a `.circle` class for this if you want to use it.

**Comment by gvn** [comment]
A couple minor nits, but R+!

done done
